/* wickra-compile C ABI — generated by cbindgen; do not edit by hand. */

#ifndef WICKRA_COMPILE_H
#define WICKRA_COMPILE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// A required pointer argument (`handle` or `cmd_json`) was null.
#define WICKRA_COMPILE_ERR_NULL -1

// `cmd_json` was not valid UTF-8.
#define WICKRA_COMPILE_ERR_UTF8 -2

// A panic was caught at the FFI boundary.
#define WICKRA_COMPILE_ERR_PANIC -3

// An opaque handle to a compiler instance. Created by [`wickra_compile_new`]
// and destroyed by [`wickra_compile_free`]; never dereferenced by the caller.
//
// The handle caches the most recent command's response in `pending` so the
// two-call length protocol does not execute the command twice — important
// because some commands (`compile` with a real build, `artifact_bytes`) are
// stateful. The cache is keyed on the raw command bytes and cleared once the
// response has been delivered.
typedef struct WickraCompiler WickraCompiler;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// Construct a compiler handle. Never null except on allocation failure. Free it
// with [`wickra_compile_free`].
WickraCompiler *wickra_compile_new(void);

// Destroy a compiler handle. Null is a no-op.
//
// # Safety
// `handle` must be null or a handle previously returned by
// [`wickra_compile_new`] and not already freed.
void wickra_compile_free(WickraCompiler *handle);

// Apply a command JSON and write the response JSON into the caller's buffer.
//
// Returns the response length in bytes (excluding the terminating NUL), or a
// negative error code. When `len < cap`, the response and a trailing NUL have
// been written to `out`; otherwise `out` is left untouched. Pass `out = NULL`,
// `cap = 0` to query the length.
//
// # Safety
// `handle` must be a valid handle; `cmd_json` a valid NUL-terminated C string;
// `out` either null or a writable buffer of at least `cap` bytes.
int32_t wickra_compile_command(WickraCompiler *handle,
                               const char *cmd_json,
                               char *out,
                               uintptr_t cap);

// Copy the bytes of an open artifact handle into `out`.
//
// The `byte_handle` is the `handle` field from a prior `artifact_bytes`
// command's response. Returns the total byte length, or
// [`WICKRA_COMPILE_ERR_NULL`] if the handle is unknown. When `len <= cap` the
// bytes are copied; otherwise `out` is left untouched (the caller knows `len`
// from the `artifact_bytes` response and re-calls).
//
// # Safety
// `handle` must be a valid handle; `out` either null or a writable buffer of at
// least `cap` bytes.
int64_t wickra_compile_artifact_read(WickraCompiler *handle,
                                     uint64_t byte_handle,
                                     uint8_t *out,
                                     uintptr_t cap);

// The library version as a static NUL-terminated string (do not free).
const char *wickra_compile_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WICKRA_COMPILE_H */
